# Generated by Django 3.1.4 on 2020-12-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mensalista_movimento_parametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
